# -*- coding: utf-8 -*-
"""EDA on Retail Sales Data (Level 1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sc6mK6d7i5Q5G5M7zWxAkM0BouiMjwGd
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/dataset/retail_sales_dataset.csv')
df.head()

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/dataset/retail_sales_dataset.csv')

info = df.info()
describe = df.describe(include='all')
missing = df.isnull().sum()

info, describe, missing

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/dataset/retail_sales_dataset.csv')

# Convert Date to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Create new columns
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

# Check duplicates
duplicates_count = df.duplicated().sum()

# Remove duplicates if any
df_cleaned = df.drop_duplicates()

duplicates_count, df_cleaned.head()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/dataset/retail_sales_dataset.csv')
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month

# 1. Monthly Sales Trend
plt.figure()
monthly_sales = df.groupby('Month')['Total Amount'].sum()
monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.show()

# 2. Product Category Count
plt.figure()
category_counts = df['Product Category'].value_counts()
category_counts.plot(kind='bar')
plt.title("Product Category Distribution")
plt.xlabel("Category")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# 3. Gender-wise Total Sales
plt.figure()
gender_sales = df.groupby('Gender')['Total Amount'].sum()
gender_sales.plot(kind='bar')
plt.title("Gender-wise Sales")
plt.xlabel("Gender")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.show()

# 4. Age Distribution
plt.figure()
df['Age'].plot(kind='hist', bins=10)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()